// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Notification struct {
	NotificationID uuid.UUID        `json:"notification_id"`
	UserID         uuid.UUID        `json:"user_id"`
	Title          pgtype.Text      `json:"title"`
	Message        pgtype.Text      `json:"message"`
	Type           string           `json:"type"`
	IsRead         bool             `json:"is_read"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}
