// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	GetNotificationsList(ctx context.Context, userID uuid.UUID) ([]Notification, error)
}

var _ Querier = (*Queries)(nil)
